name: Create Production Builds

on:
  workflow_dispatch: {}

jobs:
  build_android:
    type: build # This job type creates a production build for Android
    params:
      platform: android
      profile: production
