export const EVENT_TYPES = [
  "organization.created",
  "organization.status.updated",
  "organization.updated",
  "organization.deleted",
  "account.created",
  "account.status.updated",
  "account.updated",
  "account.deleted",
  "audit.created",
  "audit.rescheduled",
  "audit.completed",
  "audit.notes.updated",
  "audit.floorsVisited.updated",
  "audit.account.reassigned",
  "contact.created",
  "contact.method.added",
  "contact.method.updated",
  "contact.updated",
  "contact.deleted",
  "account.contact.linked",
  "account.contact.unlinked",
  "account.contact.setPrimary",
  "account.contact.unsetPrimary",
  "note.created",
  "note.updated",
  "note.deleted",
  "note.linked",
  "note.unlinked",
  "interaction.linked",
  "interaction.unlinked",
  "interaction.scheduled",
  "interaction.rescheduled",
  "interaction.status.updated",
  "interaction.logged",
  "interaction.updated",
  "interaction.deleted",
  "code.created",
  "code.updated",
  "code.encrypted",
  "code.deleted",
  "settings.security.updated",
  "device.registered",
] as const;

export type EventType = (typeof EVENT_TYPES)[number];
