/**
 * Centralized Error Codes
 * Provides constants for consistent error handling across the application
 */

// Database Error Codes
export const DB_ERROR_CODES = {
  // General
  DB_ERROR: 'DB_ERROR',
  DB_NOT_INITIALIZED: 'DB_NOT_INITIALIZED',
  DB_INIT_FAILED: 'DB_INIT_FAILED',

  // Query Errors
  QUERY_FAILED: 'QUERY_FAILED',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',

  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_PARAM: 'INVALID_PARAM',
  REQUIRED_FIELD: 'REQUIRED_FIELD',

  // Constraint Errors
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  UNIQUE_CONSTRAINT: 'UNIQUE_CONSTRAINT',
  NOT_NULL_CONSTRAINT: 'NOT_NULL_CONSTRAINT',

  // Record Errors
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',

  // Migration Errors
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  MIGRATION_ROLLBACK_UNSUPPORTED: 'MIGRATION_ROLLBACK_UNSUPPORTED',
  MIGRATION_ENTRY_INVALID: 'MIGRATION_ENTRY_INVALID',
  MIGRATION_DUPLICATE: 'MIGRATION_DUPLICATE',
};

// Service Error Codes
export const SERVICE_ERROR_CODES = {
  // General
  SERVICE_ERROR: 'SERVICE_ERROR',
  OPERATION_FAILED: 'OPERATION_FAILED',

  // Authentication
  AUTH_FAILED: 'AUTH_FAILED',
  INVALID_PIN: 'INVALID_PIN',
  BIOMETRIC_FAILED: 'BIOMETRIC_FAILED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // File Operations
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_READ_FAILED: 'FILE_READ_FAILED',
  FILE_WRITE_FAILED: 'FILE_WRITE_FAILED',
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',

  // Permissions
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PERMISSION_NOT_GRANTED: 'PERMISSION_NOT_GRANTED',

  // Notifications
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',
  NOTIFICATION_PERMISSION_DENIED: 'NOTIFICATION_PERMISSION_DENIED',

  // Sync Operations
  SYNC_FAILED: 'SYNC_FAILED',
  IMPORT_FAILED: 'IMPORT_FAILED',
  EXPORT_FAILED: 'EXPORT_FAILED',

  // Backup/Restore
  BACKUP_FAILED: 'BACKUP_FAILED',
  RESTORE_FAILED: 'RESTORE_FAILED',
  INVALID_BACKUP_FORMAT: 'INVALID_BACKUP_FORMAT',
};

// UI/Validation Error Codes
export const UI_ERROR_CODES = {
  // Form Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_DATE: 'INVALID_DATE',
  FIELD_REQUIRED: 'FIELD_REQUIRED',

  // User Actions
  OPERATION_CANCELLED: 'OPERATION_CANCELLED',
  TIMEOUT: 'TIMEOUT',

  // Component Errors
  RENDER_ERROR: 'RENDER_ERROR',
  STATE_ERROR: 'STATE_ERROR',
};

// Network Error Codes (for future use)
export const NETWORK_ERROR_CODES = {
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',
  NO_CONNECTION: 'NO_CONNECTION',
  SERVER_ERROR: 'SERVER_ERROR',
};

// Export all codes as a single object for convenience
export const ERROR_CODES = {
  ...DB_ERROR_CODES,
  ...SERVICE_ERROR_CODES,
  ...UI_ERROR_CODES,
  ...NETWORK_ERROR_CODES,
};

export default ERROR_CODES;
