import { t } from "@i18n/index";

export const useBackupLabels = () => ({
  title: t("backup.title"),
  exportTitle: t("backup.export.title"),
  exportDescription: t("backup.export.description"),
  exportAction: t("backup.export.action"),
  exportSuccessTitle: t("backup.export.successTitle"),
  exportSuccessMessage: t("backup.export.successMessage"),
  exportShareUnavailable: t("backup.export.shareUnavailable"),
  exportErrorMessage: t("backup.export.error"),
  keySectionTitle: t("backup.key.title"),
  keySectionDescription: t("backup.key.description"),
  keyRevealAction: t("backup.key.action"),
  keyModalTitle: t("backup.key.modalTitle"),
  keyModalMessage: t("backup.key.modalMessage"),
  keyCopyAction: t("backup.key.copy"),
  keyCopySuccessTitle: t("backup.key.copySuccessTitle"),
  keyCopySuccessMessage: t("backup.key.copySuccessMessage"),
  keyCopyError: t("backup.key.copyError"),
  keyBiometricUnavailable: t("backup.key.biometricUnavailable"),
  keyBiometricDisabled: t("backup.key.biometricDisabled"),
  keyBiometricFailed: t("backup.key.biometricFailed"),
  keyLoadError: t("backup.key.loadError"),
  keyAuthReason: t("backup.key.authReason"),
  importTitle: t("backup.import.title"),
  importDescription: t("backup.import.description"),
  importFileLabel: t("backup.import.file.label"),
  importFilePlaceholder: t("backup.import.file.placeholder"),
  importFileSelected: (name: string) =>
    t("backup.import.file.selected", { name }),
  importModeLabel: t("backup.import.mode.label"),
  importModeMerge: t("backup.import.mode.merge"),
  importModeReplace: t("backup.import.mode.replace"),
  importModeMergeHint: t("backup.import.mode.mergeHint"),
  importModeReplaceHint: t("backup.import.mode.replaceHint"),
  importAction: t("backup.import.action"),
  importNoFile: t("backup.import.noFile"),
  importSuccessTitle: t("backup.import.successTitle"),
  importSuccessMessage: t("backup.import.successMessage"),
  importErrorMessage: t("backup.import.error"),
  importReplaceTitle: t("backup.import.replace.title"),
  importReplaceMessage: t("backup.import.replace.message"),
  importReplaceConfirm: t("backup.import.replace.confirm"),
  okLabel: t("common.ok"),
  cancelLabel: t("common.cancel"),
  errorTitle: t("common.error"),
});
